server:
  port: 8901

# 可申请API秘钥；https://ai.google.dev/gemini-api
google:
  api:
    base-url: https://generativelanguage.googleapis.com
    key: AIzaSyDF6JnvFx7xWEsARSGosNmvTU3ZoCwo-mc
  cloud:
    project: xfg-google-adk

logging:
  level:
    root: info
  config: classpath:logback-spring.xml