server:
  port: 8901

logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# Google ADK Configuration
google:
  api:
    key: AIzaSyDF6JnvFx7xWEsARSGosNmvTU3ZoCwo
  cloud:
    project: xfg-google-adk